source-context: ""
destination-context: ""
source-kubeconfig: ""
destination-kubeconfig: ""
source-velero-helm-release-name: ""
source-velero-namespace: ""
destination-velero-namespace: ""
restore-name: ""
backup-name: ""
schedule-name: ""
item-operation-timeout: 4h
included-namespaces: []
excluded-namespaces: []
included-resources: ["*"]
excluded-resources: []
include-cluster-resources: false
label-selector: {}
or-label-selectors: {}
namespace-mapping: {}
restore-pvs: true
preserve-node-ports: true
existing-resource-policy: "none"